# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5584b0651079df815a8b8627112f4dbb783082f76e82ec87f9dbb90e1e267e890c62952556d3dab91e74d6da0d88fee7f492065d18ec7fb8b34e525b90575e

test:
  secret_key_base: 601eea3f515c00f2cca85bfacbeb45664d3985494133810c2017a133c772c1a6de449881dec2588571bd4f8eefc4e822635dea9390271ea767261411528ad5d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
